# Generated by Django 4.2.7 on 2023-11-02 05:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0002_productline_order_alter_productline_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productline",
            name="order",
            field=models.PositiveBigIntegerField(),
        ),
    ]
