# Generated by Django 4.2.7 on 2023-11-02 05:59

from django.db import migrations
import product.fields


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0003_alter_productline_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productline",
            name="order",
            field=product.fields.OrderField(blank=True),
        ),
    ]
