# Generated by Django 4.2.6 on 2023-11-04 08:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0003_brand_is_active_category_is_active"),
        ("product", "0004_alter_productline_order"),
    ]

    operations = []
